services:
  - type: web
    name: vahanbridge-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: shinkansen.proxy.rlwy.net
      - key: DB_PORT
        value: "10642"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: swckvNwlKDIsFHulxjLYpdJAiuaXBOEw
      - key: DB_NAME
        value: railway
      - key: FRONTEND_URL
        value: https://vaahanbridge.netlify.app
      - key: UPLOAD_DIR
        value: ./uploads
